image: barichello/godot-ci:3.4.2

variables:
  EXPORT_NAME: gittest

stages:
  - build
  - deploy

godot.build:
  stage: build
  script:
    - mkdir -v -p build
    - godot -v --export "HTML5" ./build/html/$EXPORT_NAME.html
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/*

godot.deploy:
  stage: deploy
  dependencies:
    - build
  script:
    - rm -rf public
    - cp -r build public
  artifacts:
    paths:
      - public
  only:
    - develop